version: 2

sources:
  - name: gcs_raw
    description: "Données brutes stockées dans GCS (Delta Lake) - Couche Bronze"
    tables:
      - name: sp500_stock_prices
        external_location: "gs://finance-data-lake-unique-id/bronze/sp500_stock_prices"
      - name: data_raw_2b
        external_location: "gs://finance-data-lake-unique-id/bronze/data_raw_2b"
      - name: data_raw_etf
        external_location: "gs://finance-data-lake-unique-id/bronze/data_raw_etf"
      - name: data_raw_sp500
        external_location: "gs://finance-data-lake-unique-id/bronze/data_raw_sp500"

  - name: gcs_silver_ext
    description: "Tables Silver rééchantillonnées (générées par Spark ou DuckDB) - Entrées pour Gold"
    tables:
      - name: data_raw_2b_weekly
        external_location: "gs://finance-data-lake-unique-id/silver/data_raw_2b_weekly"
      - name: data_raw_etf_weekly
        external_location: "gs://finance-data-lake-unique-id/silver/data_raw_etf_weekly"
      - name: data_raw_sp500_weekly
        external_location: "gs://finance-data-lake-unique-id/silver/data_raw_sp500_weekly"
      - name: sp500_stock_prices_weekly
        external_location: "gs://finance-data-lake-unique-id/silver/sp500_stock_prices_weekly"
